---
language: node_js
node_js: "stable"
node_js:
  - 8
addons:
  firefox: "49.0"
script: npm run bootstrap --scope react-habitat* && npm run test
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
