---
language: node_js
node_js: "stable"
dist: trusty
sudo: required
addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
